# Generated by Django 4.2.30 on 2026-05-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, verbose_name='Colores detallados'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list, verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list, verbose_name='Talles disponibles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='swatches',
            field=models.JSONField(blank=True, default=list, verbose_name='Colores (hex)'),
        ),
    ]
